### ISSUE TITLE
REQ-0-assertions

### ISSUE THREAD

**Issue by rubdos** [vitiral/artifact#102]
Hi,

> "Assertions **will** be used throughout the artifacts to mean:" [...]

Are these words somehow checked by artifact?
Can we make something like that happen?
If artifact would be able to read words like *will*, *shall*, *should* and would be able to interpret them, and export/visualize them on the export, that would be pretty awesome.

It's just a random thought, I think this might lead to an interesting discussion.

Ruben

**Comment by vitiral** [comment]
After I learn more about machine learning I would love to have a program that reads your requirements and helps you with verification. Not in scope right now though. For now, artifact is "just" text fields, and humans have to review it.

**Comment by vitiral** [comment]
I don't want to discourage your ideas, but such an effort will never be in scope for the base project, and I'm years away from even thinking about starting it.

**Comment by rubdos** [comment]
> I don't want to discourage your ideas, but such an effort will never be in scope for the base project, and I'm years away from even thinking about starting it.

Yeh, I supposed so. No worries. I still have an idea that I'd like to discuss on gitter when you're back
