### ISSUE TITLE
Visualise inter-requirement dependencies

### ISSUE THREAD

**Issue by rubdos** [vitiral/artifact#103]
I'm very sorry for spamming your issues/inbox so much, but I really have lots of ideas :/

I was thinking that certain REQ's depend on some other REQ's (possibly *n*-to-*n* relations, possibly even cyclic. That should be up to the developer, I think :) ).

Would it be interesting/feasible to implement something like `part-of`, but for a list of dependencies? E.g. a certain module A could need module X and module Y before it's able to implement it, but it might not necesserilly be a `part-of` it.

This could also be expressed in the web-ui, and in the output of `art ls`, such that if you navigate to a REQ, you can see on what it depends, and therefore why it hasn't been implemented yet.

**Comment by vitiral** [comment]
You can specify multiple values in partof. 

You can also reference other requirements in the text field with `[[...]]`

**Comment by vitiral** [comment]
We COULD have artifact use the reference links in the text and partof fields to visualize how artifacts are connected. That is something I want I  the web UI that is not in a  requirement yet

**Comment by vitiral** [comment]
It should be more possible after simplifying the loading procedure (which I did a few weeks ago). Hopefully it can be completely handled in the `load_repo` function. I would still use the ProjectText object though

**Comment by vitiral** [comment]
we could leverage #158 to do this fairly trivially

**Comment by vitiral** [comment]
we could leverage #158 to do this fairly trivially (I think)

**Comment by vitiral** [comment]
done! this is the primary "search" interface in 2.0.0
