### ISSUE TITLE
reference in text: broken hyperlinks

### ISSUE THREAD

**Issue by einsweniger** [vitiral/artifact#105]
When using references in the artifact text with i.e. `[[REQ-1]]`, the hyperlink always refers to the filesystem root or server root instead of the page:

Observable on http://vitiral.github.io/artifact/#artifacts/req-artifact:
`[[REQ-1]]` links to
vitiral.github.io/#artifacts/req-1
instead of
vitiral.github.io/**artifact/**#artifacts/

**Comment by vitiral** [comment]
Whoops! Not that they DO work when opening the index.html directly (which is why I missed it)

**Comment by vitiral** [comment]
`model.location.origin ++ "/" ++ artifactsUrl ++ "/" ++ addrName`

Is what does this. Location is this object

http://package.elm-lang.org/packages/elm-lang/navigation/2.1.0/Navigation#Location

Currently I use origin... What should i be using instead?

**Comment by vitiral** [comment]
It looks like I want to do host + pathname https://developer.mozilla.org/en-US/docs/Web/API/Location
