### ISSUE TITLE
"art fmt" error displays twice

### ISSUE THREAD

**Issue by jmcquown** [vitiral/artifact#108]
When "art fmt" is run without an option (-l, -d, -w), the error message will display twice.

![image](https://cloud.githubusercontent.com/assets/9219316/23981513/80212f32-09dd-11e7-951b-120d1d73a552.png)

**Comment by jmcquown** [comment]
Something else that happens related to this is that when "art fmt -h" is run the help information for the "art fmt" command displays three times. Once to display the help information, but then two more times because of the issue above when the error message is displayed twice. For some reason each error message is accompanied by the "art fmt" help information.

![image](https://cloud.githubusercontent.com/assets/9219316/23981630/67bcedd6-09de-11e7-8a9d-fec134591a81.png)

**Comment by jmcquown** [comment]
Sorry for the potential confusion, I forgot to update to the newest artifact release. Please ignore

**Comment by vitiral** [comment]
this should have been fixed a while ago, were you running a version from more than a month ago?

**Comment by jmcquown** [comment]
So yeah I realized about 20 minutes after submitting the issue I remembered I submitted almost the exact one a long time ago. Then I realized that I hadn't been keeping up with any of the updates, only doing git pull.

Sorry for any confusion I may have caused, I just forgot that that there's more to updating than just doing git pull 😅
