### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by jmcquown** [vitiral/artifact#117]
Go through current design [document](https://docs.google.com/document/d/1aOKzuy-eSGggwQKpaitVGqk7OJ7JZCRqWaRlUgqCXlE/edit?usp=sharing) and implement everything into artifact

**Comment by vitiral** [comment]
this is going to require some work, and can be worked on by the whole team @TheAustinJones @packapotatoes 

In particular, I am concerned about the following:
- how does `table!` handle foreign keys?
- it would be worth writing the type and creating some unit tests to interact with it in basic ways
  - insert a row
  - delete the row
  - read the row
  - query a row
  - use multiple tables with foreign keys and do queries based on them

The unit tests above in particular are going to help you validate that you have some idea on how to interface with the database and is going to significantly help you write your implementation.

Again, there are now only 2 weeks left... gotta get going on this!

**Comment by packapotatoes** [comment]
for the date stamp, do we want date _and_ time, or just the date?

**Comment by vitiral** [comment]
Date and time. Personally I prefer just using the epoch and letting the application handle converting it.

**Comment by packapotatoes** [comment]
[This](http://docs.diesel.rs/diesel/associations/index.html) should be what we need for foreign keys and table relationships.

**Comment by packapotatoes** [comment]
@vitiral which of the version fields should be mandatory? (major, minor, patch, build)

**Comment by vitiral** [comment]
I would say only major

**Comment by packapotatoes** [comment]
@jmcquown @TheAustinJones I just pushed to `schema` branch two files, db.dump and notes.txt. The `notes.txt` contains instructions for how to import the db schema. I doubt this is the final schema, but hopefully this will help unify our efforts.

**Comment by vitiral** [comment]
@packapotatoes no reason to keep that in a branch, looks pretty good. Go ahead and open a pull request if it compiles and I'll merge it.

Only thing is, please move `notes.md` to `design/tracker/notes.md`.

**Comment by jmcquown** [comment]
I'm working on adding the foreign keys on the [foreign-keys](https://github.com/vitiral/artifact/tree/foreign-keys) branch
