### ISSUE TITLE
Adding test names and version number to test tracker manually vs automatically

### ISSUE THREAD

**Issue by packapotatoes** [vitiral/artifact#125]
There are two ways we could handle adding test names and version numbers:
1. An API call to AddTestRun includes the test name and version information
These inputs are checked against the appropriate tables and added if missing. A version_id is returned if the version was added.

2. A call to AddTestRun includes the test name and version_id.
These inputs are checked against the appropriate tables and returns an error if the entry is missing.
test names and version would have to be added using a separate call such as AddTest and AddVersion.

Method 1 would be more difficult to implement because it would not be possible to make an `insertable` struct directly from the input parameters. It would require parsing the parameters and building an `insertable` struct manually. It would then have to make a request to the test_name and version tables to search them, then another to add the info if it's not there.

Method 2 would be slightly easier to implement because the params could be parsed directly to an `insertable` struct. However, it would cause more work for somebody using the API because instead of using one call to add info about a test run of a new test on a new version, it would take three, one to add the version, one to add the test_name, then one to add the test_run info. On the other hand, this might help the user of the API avoid typos or other errors because they would have to explicitly add the test_name and version.

I think I am going to start by implementing method two because it can act as a base for the first method, but @vitiral, what is the preferred functionality?

Edit: I forgot that the associated artifact names should also be verified, so this applies to them too.

**Comment by packapotatoes** [comment]
Also, this is really most relevant for the version. Should a major, minor, build, patch be input in AddTestRun call, or just a version_id that represents an entry in the version table, requiring a user to keep track of arbitrary ids associated with versions?

**Comment by vitiral** [comment]
this should already be resolved by #128. let me know if that's not the case.
