### ISSUE TITLE
Global arguments not matched on in subcommands

### ISSUE THREAD

**Issue by chrisvittal** [vitiral/artifact#172]
To reproduce:
```sh
$ mkdir tmp1 tmp2
$ cd tmp1 && art init
$ cd ../tmp2 && art tutorial
$ art ls --work-tree ../tmp1
```
It should output
```
|  | DONE TEST | NAME          | PARTS   
|--|   0%   0% | REQ-purpose   | 
```
But instead, the output is from the current directory:
```
|  | DONE TEST | NAME            | PARTS   
|--|   0%   0% | REQ-learn       | REQ-toml, SPC-learn, SPC-partof
|--|   0%   0% | REQ-toml        | SPC-learn
|--|   0%   0% | SPC-cmd         | SPC-cmd-ls, SPC-cmd-serve
|--|   0%   0% | SPC-cmd-ls      | 
|--|   0%   0% | SPC-cmd-serve   | 
|--|   0%   0% | SPC-example     | TST-partof
|--|   0%   0% | SPC-learn       | TST-partof
|--|   0%   0% | SPC-links       | 
|--|   0%   0% | SPC-partof      | SPC-links, TST-partof
|--|   0%   0% | SPC-tst         | 
|--|   0%   0% | SPC-valid       | 
|--|   0%   0% | TST-partof      | 
```

As the clap docs for [global](https://docs.rs/clap/2.26.0/clap/struct.Arg.html#method.global) say:
**NOTE:** Global arguments, when matched, *only* exist in the command's matches that they were matched to. For example, if you defined a `--flag` global argument in the top most parent command, but the user supplied the arguments `top cmd1 cmd2 --flag` *only* `cmd2`'s `ArgMatches` would return `true` if tested for `ArgMatches::is_present("flag")`.

**Comment by vitiral** [comment]
interesting... I think this was actually a bug on my understanding of clap. I would prefer the syntax

```
top --flag --value <VALUE> subcmd1
```

be the only one that works for these kind of commands, and other uses return an error. If later we want to support "true globals" then that is fine.

So the bug here is that the following doesn't raise an error:
```
art ls --work-tree ../tmp1
```

and that instead you should have to do
```
art --work-tree ../tmp1 ls
```

Do you think that sounds good?

**Comment by vitiral** [comment]
I'm guessing that just the `global(true)` builder call needs to be removed for this.

Also, there should be some unit tests to make sure it works as expected. [`assert-cli`](https://github.com/killercup/assert_cli) seems like a good tool for this kind of thing. I'd like to explore using it for the cli tests and maybe add a few more as well.

**Comment by vitiral** [comment]
global arguments were removed in 2.0.0
