### ISSUE TITLE
Provide default `purpose.toml` template for Rust API Guidelines

### ISSUE THREAD

**Issue by sanmai-NL** [vitiral/artifact#179]
Whenever Artifact is initialized in a Rust library project, it would be a good use and demonstration of Artifact to create a `purpose.toml` that reflects the [Rust API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/checklist.html).

**Comment by vitiral** [comment]
I'm confused what the ask here is. Do you want `artifact` to include the Guidelines checklist as separate `REQ-XXX` items?

**Comment by sanmai-NL** [comment]
Okay, so it is out of scope? It would be great if the Rust API Guidelines are used to showcase Artifact in one way or another though.

**Comment by vitiral** [comment]
If you feel it should be included in the book, feel free to [open a ticket there](https://github.com/vitiral/simple-quality/issues)
