### ISSUE TITLE
Render CommonMark in item text fields everywhere

### ISSUE THREAD

**Issue by sanmai-NL** [vitiral/artifact#180]
It appears you cannot link to e.g. online specifications in the texts describing `SPC` items. That does seem to me like a very useful feature, however. One solution would be to allow CommonMark in there.

**Comment by vitiral** [comment]
You should be able to do:

```
[SPC-foo]
text = '''

The online specification can be found [here](https://google.com)
'''
```

Note that `https://` is required for web-links.

[Here is an example of links being embeded in `text`](https://vitiral.github.io/artifact/#artifacts/spc-0)

If you mean that you can't do links in the `done` field, I just opened #181 to fix that eventually.

**Comment by sanmai-NL** [comment]
This does not work for me when using `art export html`. It shows the text in a table as plain text.

**Comment by vitiral** [comment]
Interesting -- do you mean it doesn't work from the list view when looking at `text`? I think the `text` column currently displays the raw text, which would explain that.

I'm not sure what behavior is appropriate here. I currently truncate `text` when viewing in the list to prevent it from exploding the list view.

**Comment by sanmai-NL** [comment]
Perhaps remove the text column then?

**Comment by vitiral** [comment]
Maybe... I'll have to think more about it. I allow you to search it, it would be kinda weird to not be able to view it. But that might be the right solution.

**Comment by vitiral** [comment]
see issue #193, I think we have a potential solution.
