### ISSUE TITLE
support markdown as data files

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#185]
probably make them the "default" in the future through `art init` setting them as the default in `settings.toml`

A data markdown file would look like:
```
# REQ-markdown
- partof:
  - REQ-0
  - REQ-[foo, bar]
- done: this is the optional `done` field
- plugin-attr: this entire section is actually parsed as yaml, so
    you can do pretty much whatever you want until two or more `#` on their own line.
##
The above `##` is what separates the "data" from the "text" fields. The nice thing is 
that markdown doesn't actually render an empty header!

Everything else (like this and the sentance above) is parsed as text.

## Subheader
You can have sub-headers in the text.

# SPC-markdown
partof:
- REQ-0

##
Here is some text about SPC-markdown

# REQ-top
If there are no attributes (partof, etc), you can ommit the `##` and just write text. The parser will not complain.
```
I've been thinking about this, and the parser for this is actually fairly trivial. Re-writing markdown should be relatively easy as well.

<details>
  <summary><b>Rendered</b></summary>

# REQ-markdown
- partof:
  - REQ-0
  - REQ-[foo, bar]
- done: this is the optional `done` field
- plugin-attr: this entire section is actually parsed as yaml, so
    you can do pretty much whatever you want until two or more `#` on their own line.
##
The above `##` is what separates the "data" from the "text" fields. The nice thing is 
that markdown doesn't actually render an empty header!

Everything else (like this and the sentance above) is parsed as text.

## Subheader
You can have sub-headers in the text.

# SPC-markdown
partof:
- REQ-0

##
Here is some text about SPC-markdown

# REQ-top
If there are no attributes (partof, etc), you can ommit the `##` and just write text. The parser will not complain.
</details>

**Comment by rubdos** [comment]
Hmm, I like it. Probably needs some testing to see whether it can contain all features you have in the current format, but I don't see that as a problem.

**Comment by vitiral** [comment]
I've changed the "end data" block from `---` to `###`. `###` doesn't get rendered at all in the end output, but is also a nice separator.

I'll keep experimenting, but I think this is the right approach.

**Comment by vitiral** [comment]
One thing this breaks is that you won't be able to use a top header anywhere.

I.e. this will not be allowed:
```
# REQ-foo

# Some header for REQ-foo
```
It would be *possible* to support this, but honestly it would be cluttered. This isn't backwards incompatible -- it would just mean that when a user tried to export to markdown it would throw an error (with a helpful message) and they would have to manually fix

**Comment by vitiral** [comment]
On the other hand, maybe sticking with toml is the way to go. The stuff between `# REQ-foo` and `###` *is actually data*, it's probably good for it to look like data!

<details>

# REQ-foo
partof = [
    "REQ-foo",
    "REQ-bar",
    "REQ-baz",
]
done = "this is done"
###
Here is some text
</details>

Hmm... I don't like that though, especially that the indents are deleted.

**Comment by einsweniger** [comment]
my two cents:
I like reStructuredText better, but markdown is more common.
I'm not sure if I'd describe markdown as trivially parseable, is there no crate for that?

toml isn't very pretty, and does not have many features, but it's easy to maintain and easy to parse.
md is pretty, but: there are several dialects and extensions around (eg. [man 5 pandoc_markdown](https://linux.die.net/man/5/pandoc_markdown)) and AFAIR allows to litter HTML throughout the whole document.

I'd vote to implement a very small and restrictive subset of md, to keep it maintainable. 
Maybe allow for an external parser to generate html, that can be fed back into the system.

**Comment by vitiral** [comment]
I have quite a bit of negative feelings against reStructuredText. Markdown has it's faults, but reStructuredText has way too much syntax for my taste... it's not very "clean".

Interestingly, I actually like the fact that you can insert `html` in markdown -- it is a feature I use in the web-ui to great effect.

Also, I'm not suggesting I parse the markdown exactly... the basic design would be three regexes:

- The header line
```
#\s(REQ|TST|SPC)-\w+\s*
```

- I would then pull lines into a buffer until I hit one of:
    - the "end of attributes" line
```
###+\s*
```
    - another header line

If I hit another header line, the buffer==`text`. If I hit the "end of attributes" line then I parse until a header line and that is my text.

The parsed attributes would be desrialized using a yaml library, so I wouldn't have to do much there.

Re-writing the files would be almost as easy. I don't see a lot of technical risk here.

**Comment by vitiral** [comment]
I'm looking at `###` and it ALSO inserts a line separation... annoying. Maybe attributes should just be a code block with the label `attrs`:

# REQ-foo
```
partof = [
   "REQ-bob",
   "REQ-purpose",
]
```

That would have the benefit of letting me stick with `toml` for the attributes, which would be nice.
