### ISSUE TITLE
Relicense as MIT + Apache 2.0

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#190]
I am interested in relicensing this project as dual MIT + Apache 2.0. I think the only thing required to do so is approval from those who have contributed. The following is a list of all contributors, if you could assent your approval that would be extremely helpful.

If you have any comments or concerns, please voice them!

- [x] @jmcquown
- [x] @vitiral
- [x] @packapotatoes
- [x] @porglezomp
- [x] @chrisvittal 
- [x] @rubdos
- [x] @matthewjberger
- [x] @einsweniger
- [x] @fstephany
- [x] @jplatte
- [x] @imp
- [x] @hdhoang 
- [x] @llogiq 

Sorry to everyone for the inconvenience and thank you for your contributions!

This change is mainly prompted because I would like to embed graphiz DOT language (which represents node graphs, see #158), but its license is Eclipse and cannot work with GPL.

They are working on changing it to Eclipse 2.0 (which should be simple), but the "GPL compatibility clause" is not possible to add for legacy projects, and would basically involve a complete re-licensing effort on their part as well.

### Edit: 

I checked and gerd contributed a typo fix for docs and TheAustinJones contributed code that has since been deleted

- ~~@gerd2002~~
- ~~@TheAustinJones~~

**Comment by matthewjberger** [comment]
I consent, absolutely!

**Comment by chrisvittal** [comment]
I'm willing to license my contributions under MIT + Apache 2.0.

**Comment by porglezomp** [comment]
I'm willing to license my contributions under MIT + Apache 2.0

**Comment by imp** [comment]
👍 Count me in - I'm willing to license my contributions under MIT + Apache 2.0

**Comment by jplatte** [comment]
I don't think you need to ask people like me who have only fixed typos. I am curious about what prompted this change though.

**Comment by einsweniger** [comment]
On 2017-10-23T04:39:56, Garrett Berg wrote:
> I am interested in relicensing this project as dual MIT + Apache 2.0. I think the only thing required to do so
> is approval from those who have contributed. The following is a list of all contributors, if you could
> assent your approval that would be extremely helpful.
Yes, I'm fine with relicensing.

**Comment by vitiral** [comment]
Thanks for the responses everyone!

@jplatte for now I'm just doing a broad blanket include to be on the safe side. If necessary I *may* have to strip commits and re-implement them or something -- but I really want to avoid that. (and yes, in certain cases the license probably doesn't apply -- such as when someone only changed docs which are licensed as public domain anyway).

**Comment by llogiq** [comment]
I hereby consent to relicensing my contributions to the project as MIT/Apache 2.0.

**Comment by fstephany** [comment]
Same here, I agree to relicense my (very very small) contributions as MIT + Apache 2.0. 
Thanks for all your work @vitiral !

**Comment by vitiral** [comment]
@jplatte I realized you wanted a reason why I opened this issue. I added a description at the end of the issue (I want to embed graphiz, which is Eclipse and not GPL compliant).

**Comment by rubdos** [comment]
Since it's for graphiz dot, which I approve of:

I'm willing to license my contributions under MIT + Apache 2.0.

**Comment by hdhoang** [comment]
I also sign off on this relicensing.

**Comment by packapotatoes** [comment]
I'm willing to license my contributions under MIT + Apache 2.0

**Comment by jmcquown** [comment]
I'm willing to license my contributions under MIT + Apache 2.0.

**Comment by vitiral** [comment]
Thanks everyone for your response, artifact is now relicensed!
