### ISSUE TITLE
markdown rendering in list

### ISSUE THREAD

**Issue by crackcomm** [vitiral/artifact#193]
I just discovered markdown links don't render in list view.

To be honest I think it improves the readability of the overall table - to see no links in the text.

**Comment by vitiral** [comment]
Just to make sure I understand, you mean the links in the `text` field right?

The trouble with this is: how should I truncate the *rendered* view... it's not trivial.

I'm actually considering removing the `text` field from the list view alltogether. What do you think?

**Comment by crackcomm** [comment]
Yes, I meant `text` field of an artifact. I find text field very useful and it can be disabled, I don't think there is need for removing it.

When it comes to truncating the rendered view, it is not trivial, you are right.
That's why I think it would be good idea to use CSS for this.

**Comment by vitiral** [comment]
I'm not that good at CSS. Can you use CSS to truncate?

**Comment by crackcomm** [comment]
I am no good at CSS either, I think there is `text-overflow` but I am not sure what it actually does. It's also possible to truncate with js.

**Comment by crackcomm** [comment]
I have also idea - to truncate before `\n\n`.

**Comment by vitiral** [comment]
@crackcomm I like that

**Comment by vitiral** [comment]
So, I'm thinking of doing a complete reworking of the Search view and using a node-tree that gets dynamically "pruned' as you search. You could still *search* for text/defined-in/etc, but they wouldn't be displayed (maybe they would be in the title-text).

I'm still thinking of all the details, but personally I've never found much use in the Search feature. What do you think?

**Comment by crackcomm** [comment]
I never used the search feature myself.

**Comment by vitiral** [comment]
this is fixed by removing the search feature. It is now a graphiz graph with no text.
