### ISSUE TITLE
improve "export" command help error message

### ISSUE THREAD

**Issue by crackcomm** [vitiral/artifact#197]
During `art export`

```console
(warns...)
Encountered Error:

unknown type:
```

Windows OS, I will investigate later.

**Comment by vitiral** [comment]
windows OS is not well tested, however `art export` requires a *type to export*, i.e. `art export html` (html is the only supported one ATM if I recall correctly)

**Comment by vitiral** [comment]
the error message should be improved though.

**Comment by crackcomm** [comment]
It works great when used properly 👍 

I'd suggest to use a `html` default (as a flag?).

**Comment by vitiral** [comment]
I prefer being explicit. Maybe in 5 years if `html` is really the only major export format we can make it the default...

**Comment by crackcomm** [comment]
You are right.

**Comment by vitiral** [comment]
`export` changed slightly. This is now fixed:

```
$ art export
error: The following required arguments were not provided:
    <TYPE>
    <PATH>

USAGE:
    art export <TYPE> <PATH> --verbose <verbosity>

For more information try --help
```
