### ISSUE TITLE
web-ui: think about increasing size of empty select field

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#199]
this would make it easier to... erm... select.

**Comment by vitiral** [comment]
Moved from @crackcomm

> It's shrunk for
> ![](https://i.gyazo.com/a345a7ce24a7ca2603c6d231e1c7576f.png)

> Otherwise:
> ![](https://i.gyazo.com/0173fbd435d5ca56eaaa8cd0b2f7dcb6.png)

**Comment by vitiral** [comment]
So I remember a little bit... I didn't want it to display fully when the user wasn't trying to select anything since it was displaying the same information twice. Reducing the size was basically a hack to clean up the UI.

I'm sure there is a better solution but my CSS Wizard skills are not great enough.

**Comment by crackcomm** [comment]
I don't think you need too much wizardry, just make it a separate class 😜

**Comment by vitiral** [comment]
basically I wanted to make it smaller and invisible when the user wasn't selecting it but larger and visible when the user was. For some reason I had trouble (can't remember why...). I ended up just srinking the box so you couldn't even SEE the artifact when it wasn't selected and that worked.

**Comment by crackcomm** [comment]
What do you think about using a default `Defined at:` - first from the list?

**Comment by crackcomm** [comment]
Maybe only when there is a single file, but I'd appreciate that.

**Comment by vitiral** [comment]
I'm confused, where do I put `Defined at`?

**Comment by crackcomm** [comment]
I made a screenshot yesterday for reply but I must have forgotten, sorry.

I was talking about `Create New` form and default `Defined at` input value.

**Comment by vitiral** [comment]
oh, I see. Or maybe empty but cache the last-used one and use that?

**Comment by vitiral** [comment]
Done, I removed the select UI because it didn't work in elm and I kind of like it this way. Users should be allowed to put whatever they want.

**Comment by vitiral** [comment]
It would be good to have auto-complete in the future when the rust web-dev ecosystem is more mature.

**Comment by crackcomm** [comment]
@vitiral I haven't used artifact in quite a while and I'm astounded by the progress you made, especially the graphs are infinitely useful. It could use even more graphs! 😂

**Comment by crackcomm** [comment]
Maybe in form of embedding graphs.

I must admit that this tool really speeds up implementation of systems ^^

**Comment by vitiral** [comment]
![Graphs Within Graphs](https://memegenerator.net/img/instances/82305494/graphs-within-graphs.jpg)

**Comment by vitiral** [comment]
You can put graphs in your design doc

https://vitiral.github.io/artifact/#spc-read

**Comment by crackcomm** [comment]
Yeah, I've noticed that later, awesome 👍
