### ISSUE TITLE
Make self_update optional

### ISSUE THREAD

**Issue by rubdos** [vitiral/artifact#202]
`self_update` is quite useless on package managed systems (e.g., the AUR package). Would be cool if package builders could disable this feature.

**Comment by vitiral** [comment]
Sounds good, should definitely do this

**Comment by rubdos** [comment]
I'm on it, expect PR in a few :-)

**Comment by vitiral** [comment]
`self_update` was removed in 2.0.0. If I re-add it I will make sure it is optional.
