### ISSUE TITLE
Tutorial bugs

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#205]
Hi,

I am currently trying out `art` in `1.0.1` and found two bugs in the tutorial:

* The `tutorial.toml` says I should try `art ls REQ-learn-artifact -l` but that gives me an error:

```
Encountered Error:

The following artifacts do not exists: [REQ-LEARN-ARTIFACT]
Help: consider using the -p / --pattern flag
```

* On line 193 of the `tutorial.toml` file is a command which does also fail with the error message from above.

---

Maybe it would be a nice idea to have a short `grep` script which runs all `art ls` commands from the `tutorial.toml` file on the CI infrastructure?

**Comment by vitiral** [comment]
Fix: need to change `REQ-learn-artifact` -> `REQ-learning`

Doing some kind of automation for this is a good idea.
