### ISSUE TITLE
[web ui] do NOT link when --path-url is not passed in

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#208]
The links "Defined at" and "Implemented" do not work. I did not pass `--work-tree` as it states that `cwd` is used by default ...

the link simply links back to the root document.

**Comment by vitiral** [comment]
Agh, there shouldn't be *any* links if you didn't pass `--work-tree`. I experimented with "local filesystem links" and it was a mess.

Marking as a bug.

**Comment by vitiral** [comment]
well... there are no links in 2.0 so... this bug is fixed!

Should open a new feature bug for adding links back :smile:
