### ISSUE TITLE
[config] Exclude by pattern

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#210]
I would like to exclude code paths by pattern.

Example: I have a repository which has a lot of sub-crates (50 right now). Excluding each `target` folder is possible, but there will be more crates all the time and keeping the list up to date by hand is really tiresome.

So I'd love to exclude by pattern (`*target*` for example).

**Comment by vitiral** [comment]
I agree with this feature.

I think the variables should be `exclude_code_globs` and `exclude_artifact_globs`.

I think globs are the standard, but I would like to leave the door open to supporting full regexes in the future.

Thoughts?

**Comment by matthiasbeyer** [comment]
Awesome, thanks!

I am not sure how good glob libraries are in rust right now (never used one) so I cannot tell you whether you can do this easily or whether you have to implement your own glob-parsing. Regex support (`regex` crate) on the other hand is very good right now, though I doubt that we need more "functionality" in the pattern than globs.

I leave it up to you. :smile:

**Comment by vitiral** [comment]
This is a dup of #196, closing.

There is at least one good glob crate: https://crates.io/crates/glob
