### ISSUE TITLE
Markdown format

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#211]
Right now, the markdown format looks like this:

```md
# Header
structured: data
###

free text
```

Which is, from a visual point, rather bulky, IMHO. I'd like to suggest another format (which is better readable and supports structured data in a nicer way):

```md
---
<TOML>
---
<Markdown>
```

So basically like this:

```md
---
[some]
value = 1
---

Free text
```

See [here](https://github.com/matthiasbeyer/imag/blob/master/lib/core/libimagstore/src/util.rs#L44) for some logic how to split header and content programmatically.

**Comment by matthiasbeyer** [comment]
I totally forgot that one may have several entries in one file and one header for each "# REQ-" (for example) would be needed. That complicates things, of course. I did not think about that, sorry.

Either way, you might get inspired to use TOML for the structured data anyways! :smile:

**Comment by vitiral** [comment]
So the reasons markdown was chosen are in #185. I should probably migrate those reasons to the design docs.

The reason I am not using toml is because yaml *renders* correctly in markdown. See that issue for more details.

If you still disagree, please reopen! I would love to hear more feedback.

**Comment by matthiasbeyer** [comment]
After working a bit more wort artifact, I have to admit that I rather like the current format. 

Thanks for explanation and closing this! :+1:
