### ISSUE TITLE
[cli] Provide options to disable columns

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#213]
The CLI currently provides flags for adding more output columns (`-DPOLT`) though no option for removing columns from the output.

Usecase: I have `TST` entries with _many_ parts. The output wraps several times (on a 1080p monitor with normal text size I get lines that wrap 6 times because of >30 parts).

**Comment by vitiral** [comment]
I'm unsure what you would like.

The "default" view is name+parts
```
# art ls                                                                                                                                                                              
|  | DONE TEST | NAME                    | PARTS                                                                                                                                                                  
|--|  83%  71% | REQ-data                | REQ-data-family, REQ-data-type, SPC-data
```

If you want just one of them, you specify it:
```
# art ls -L                                                                                                                                                                           
|  | DONE TEST | NAME                    | IMPLEMENTED  
```

When you pass the `-A` flag, additional flags disable columns. Interestingly, if you try to disable all of them it still displays `parts`, which is **definitely a bug**:

```
art ls -ADPOLT
|  | DONE TEST | NAME                    | PARTS   
|--|  83%  71% | REQ-data                | REQ-data-family, REQ-data-type, SPC-data
```

Do you mean you would like to ONLY display the name? I don't think that is currently supported. I could add a
`-N` flag, but then I would have to support that *removing* the name when used with `-A`, which I suppose is fine (maybe someone might want to do that?).

**Comment by matthiasbeyer** [comment]
:curly_loop: 

I missed the "deactivate" in the help line... I should read more carefully.

```
    -A, --all       "all" fields. If set, additional field flags will *deactivate* fields
```

Everything is right. Do you want to close this or leave it open for the found bug?

**Comment by vitiral** [comment]
I think the parts bug is fixed

**Comment by vitiral** [comment]
oh wait, nevermind. Deactivating only doesn't work for subnames+impl (new fields!)

**Comment by vitiral** [comment]
and... nevermind again. It's just that subnames+impl are not documented so I missed them. This works:

```
$ art ls -A -NFPOTIS
spc%  tst%
60.0  34.7
45.7  33.7
```
