### ISSUE TITLE
[Idea] Helper tool for CI automation

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#217]
This is just a brain-dump and not a feature request or something like this.

## Idea

It would be nice to have a helper tool or script which can be used to compare two git versions for overall TST percentage.

## Purpose

The idea would be to integrate this tool into CI in the following way: Either, the pull-request/branch changes the `./design` subdirectory (thus adding new requirements, changing old requirements, etc) or the percentage of green tests does _not_ decrease.

This would yield the following benefits:

* A branch/pull-request either adds new requirements, specifications and tests (decreasing overall percentage -> allowed), or
* A change does not break any requirements, specifications or tests

## Sidenotes

Some sidenotes.

### Input/Output of the tool

The tool needs basically two input parameters: 

* The base branch (the merge-base)
* The commit to test against

Then it figures out which files changed:

* If the changed files are _only_ in the `./design` directory (or whatever is configured as artifacts directory), a decreasing overall percentage is allowed
* If there are no changes to `./design`, a decreasing percentage is not allowed
* If there are changes to `./design` _and_ outside of this directory, ... what? (We have to think about this a bit more)

The output of the tool should be a nice message what it concluded and a exit-status which can be used to abort CI.

### Realization

I would love to try this out in a `post-receive` git hook, so I would consider "bare repository support" a fundamental feature.

**Comment by vitiral** [comment]
This is the exact kind of things that an external tool/plugin should handle! I don't want any kind of revision control integration in artifact itself.

Closing this issue, but please feel free to implement this as a separate project. The `artifact-data` library currently under development will make implementing such a thing more possible.

There is currently no design for plugins, but it will be in the rewrite of the CLI (comming soon!)

**Comment by matthiasbeyer** [comment]
Thanks for closing this. I thought about this myself though was not sure.

I opened this issue to communicate the idea , I will now put this into my local taskwarrior to remind myself of it. :+1:
