### ISSUE TITLE
[cli] `art ls` with search pattern and `-c` panics

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#218]
`art ls -c "<" stdcli` or `art ls stdcli -c "<"`

gives:

```
ERROR: Invalid artifact name: "stdcli"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(CmdError("Invalid artifact name: \"stdcli\""), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by vitiral** [comment]
so the error is correct. You need to pass the `--pattern` flag. We should improve that error.

Otherwise the panic will be handeld by #222.

Leaving open to improve that error message.

**Comment by vitiral** [comment]
actually closing in favor of #222 and duplicate #216
