### ISSUE TITLE
type annotations required: cannot resolve `std::path::Component<'_>: std::convert::AsRef<_>`

### ISSUE THREAD

**Issue by talios** [vitiral/artifact#227]
Discovered artifact the other day and looks impressive, doing a `cargo install artifact-app` ( using rust nightly ) fails to compile currently with:

```rust
error[E0283]: type annotations required: cannot resolve `std::path::Component<'_>: std::convert::AsRef<_>`
  --> src/utils.rs:40:38
   |
40 |                     remaining.push(a.as_ref());
   |                                      ^^^^^^

error: aborting due to previous error
```

**Comment by vitiral** [comment]
It compiles and tests on stable and the pinned nightly `rustc 1.21.0-nightly (7eeac1b81 2017-08-30)`

Difference in behavior between stable and nightly are typically a rust bug. Please open an issue [over there](https://github.com/rust-lang/rust/issues), they would love to hear about it!

**Comment by jck** [comment]
This issue exists with stable `rustc 1.25.0`
