### ISSUE TITLE
ls should output nothing when there are no elements

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#25]
This still outputs the header:
```
# rst ls REQ-DNE -p
|  | DONE TEST | ARTIFACT NAME                                 | PARTS   | DEFINED 
```
Nothing should be printed in this case.

Also create a unit test validating this behavior

**Comment by vitiral** [comment]
relevant code is in `src/cmd/ls.rs`

**Comment by packapotatoes** [comment]
Above it says 
```
# rst ls REQ-DNE -p
```
outputs the header only. But,
```
rst ls REQ-DNE'
```
produces
```
|  | DONE TEST | ARTIFACT NAME                                 | PARTS   | DEFINED
Encountered Error:

the following artifacts do not exists: The following artifacts to not exist: [REQ-DNE]
```
Should this error be displayed when -p is not set?

**Comment by vitiral** [comment]
yes, the error is correct when -p is not set. 

(as a side note, it should also output no header when there was an error)

You are going to have some merge conflicts, as I had to add the `--type` flag and it touched where you will be changing
