### ISSUE TITLE
windows: paths have `/` in certain places

### ISSUE THREAD

**Issue by packapotatoes** [vitiral/artifact#34]
The 'implemented-at' entry shows a '/' between the current folder and beginning of path from there.

Example:
Shows 
```
implemented-at: C:\projects\rst/src\ui\mod.rs
``` 
when running from within rst folder.
Should be
```
C:\projects\rst\src\ui\mod.rs
```

**Comment by vitiral** [comment]
I'm guessing this is a windows-only bug. Thanks for opening.

**Comment by vitiral** [comment]
I think I figured out what this is `code_paths` is defined as `code_paths = ["{repo}/src", ...` which is where the path is getting that `/` character.

I need to convert those to platform specific paths first..

**Comment by vitiral** [comment]
@packapotatoes can you clone the repo at the windows branch and run `ls` with that? Everything should be fixed (and it compiles!)

**Comment by vitiral** [comment]
I feel pretty confident this will do it. Going to merge -- let me know if there are still issues
