### ISSUE TITLE
1.0: create a logo for artifact

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#47]

**Comment by vitiral** [comment]
I'm thinking a fusion of a [gear][1] + [lightbulb][2] might work:

[1]: http://www.flaticon.com/free-icon/settings_126472#term=gear&page;=1&position;=2
[2:] http://www.flaticon.com/free-icon/lightbulb_44635#term=lightbulb&page;=1&position;=92

**Comment by packapotatoes** [comment]
The logo as it stands is [here](https://drive.google.com/file/d/0B8kc7Cya04RSMUFvWFUzRGxudDg/view?usp=sharing). Any thoughts or suggestions? I made the bounding box a little shorter to match the shape of the turtle. If this looks good, I can very easily export it in different sizes and formats if you let me know what you want. I can also easily make the white transparent if you want that for any uses.

**Comment by packapotatoes** [comment]
![artboard 1sm](https://cloud.githubusercontent.com/assets/14239437/24116804/45dfef3a-0d7e-11e7-97ff-3d8482c9db65.png)
![artboard 1](https://cloud.githubusercontent.com/assets/14239437/24116803/45df1bdc-0d7e-11e7-9c1c-d866b816afad.png)

**Comment by vitiral** [comment]
Awesome! What should her name be? (I think it's a she)

**Comment by vitiral** [comment]
Some name possibilities for the female logo:
- Terra
- Arty
- [Lao](https://en.wikipedia.org/wiki/Laozi) chinese god of knowledge

**Comment by vitiral** [comment]
I think I'm going to name the logo after my daughter, Tula!

**Comment by packapotatoes** [comment]
Love it

**Comment by jmcquown** [comment]
Great choice
