### ISSUE TITLE
TT: Create and Write Initial High Level Design Document

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#59]
This can be done in a google doc. Please post the link here. Call it "Test Tracking Design Document".

This should cover
- the purpose of the test tracking tool
- high level overview of the implementation (will you use a database?)
- initial stab at sql tables that will be used

- @jmcquown will take lead creating and writing the first draft
- @packapotatoes will provide initial review.

**Comment by jmcquown** [comment]
https://docs.google.com/document/d/1aOKzuy-eSGggwQKpaitVGqk7OJ7JZCRqWaRlUgqCXlE/edit?usp=sharing

**Comment by vitiral** [comment]
done!
