### ISSUE TITLE
TT: setup initial repository config

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#60]
- create and push a branch called "server"
- add necessary diesel dependencies to `Cargo.toml`
- create the "test-name" table -- table with two columns, name and id
- create an API call to read all the names
- create an API call to add a name to the table

**Comment by packapotatoes** [comment]
I'm working on setting up this branch with these initial things, but I have a few questions:

* What should a call to this API look like?
  * What I have currently copies the diesel tutorial very closely (ex: to show tests run `cargo run --bin show_tests`) I don't think this is what we want, but it's the first thing I as able to get working.
* Where should the database be stored and when should it be created?
  * currently `echo DATABASE_URL=postgres://username:password@localhost/artifact > .env` has to be run to save the username/password and database address. This doesn't seem optimal, but I don't know how it could be improved. 
  * must run `diesel migration run` to set up the database with the test_name table

* File structure -- where should the files for this go?
  * a tracker module?
  * currently the files are kind of all over the place

Given those limitations, I can add a test name to the table, and show all stored tests. 

I'm about to push what I did. It's a start, but it probably needs serious refactoring.

**Comment by packapotatoes** [comment]
Could you give an example of what a current api call to the web server looks like? I'm having trouble tracing the code

**Comment by vitiral** [comment]
the connection is made in `src/api/mod.rs`:

```
    let endpoint = "/json-rpc";
    server.get(endpoint, handle_artifacts);
    server.put(endpoint, handle_artifacts);
    server.options(endpoint, handle_options);
    ...
    server.listen(addr).expect("cannot connect to port");
```

The default `addr` is located in `src/cmd/server.rs`
```
pub fn get_cmd(matches: &ArgMatches) -> Cmd {
    Cmd {
        addr: matches.value_of("addr").unwrap_or("127.0.0.1:4000").to_string(),
        edit: matches.is_present("edit"),
    }
}
```

So a typical request would be made against `127.0.0.1:4000/json-rpc` with a payload of the [json-rpc](http://www.jsonrpc.org/specification) specification. The only supported "method" is currently "GetArtifacts" which does not accept any "params".

**Comment by packapotatoes** [comment]
I'm still confused about some things, but I'm having trouble finding the words, so here goes....

I understand that to make a request, a json-rpc request object is sent to the api server, which returns a json-rpc response object. What I'm not clear on is where/when the server runs, and how it receives requests. 

The code you quoted above uses Nickel. From what I can tell, this is what receives and handles api calls. Is this correct? Should this code be extended by adding "method"s that deal with test tracking?

Currently, if I wanted to make an API call to GetArtifacts, what steps would I take?

**Comment by vitiral** [comment]
sorry I forgot to get back to you here. There is a bug in mainline that I am fixing and then I will give you a brief tutorial.

**Comment by vitiral** [comment]
I just fixed the "serve" command and pushed a fix. I also added a script with documentation to `scripts/api.py`. You need the `requests` module installed with `pip install requests` but otherwise you should be good to go!

**Comment by vitiral** [comment]
closing all test tracker bugs for now. Need to think how it should be designed and whether it should actually exist in artifact propper or as a separate app.
