### ISSUE TITLE
Have a "done" attribute in toml artifacts

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#66]
There are use cases where

- an artifact is "defined done" like a process or documentation artifact
- an artifact is "done" at a link outside of source code. 

The suggestion is to add a "done" attribute which accepts any arbitrary string. If the done flag is set the artifact will be considered 100% implemented AND tested

# Possible alternatives

Also add a "test" or "tested" flag to set the test percentage separately. You may want to test it internally after all.

The name could be
- finished 
- impl(emented) 
- complete

**Comment by dead10ck** [comment]
Both of those sound good, though it might be useful to be able to specify a specific percentage, for cases where estimation is necessary.

**Comment by vitiral** [comment]
Another use case: if people want to use artifact for large, existing codebases, the prospect of retroactively tracking down everywhere these tags go could be daunting. 

ya, it would be nice to be able to say "done='TODO'" when you are first using the tool.

That brings up an interesting point, where if you specify it is "done" AND have a link that I should raise an error in the check command.

**Comment by vitiral** [comment]
@dead10ck I put a lot of thought into doing just that and purposefully decided against it.

What it comes down is the question "what is this tool for?" This is a tool for writing design docs and linking to implementation. The "% done" is to just help you get a general idea of whether it is implemented or not, not be for feature tracking.

There are tons of quality issue/task/story/epic tracking tools out there, and this is a fundamentally different space. Trying to update a value *in a text file* that has a percentage would be tedious and create too many commits in your revision history. I opted for "done" to be a binary value.

I would love feedback, but that is the reasoning. I should probably put this in some kind of FAQ on the wiki

**Comment by dead10ck** [comment]
@vitiral yeah, you're right, that makes a lot of sense.
