### ISSUE TITLE
docs are hard to understand

### ISSUE THREAD

**Issue by iqualfragile** [vitiral/artifact#69]
especially it seems like the partof relationship is presented the wrong way around, the docs continiously say that parents are partof their children.

**Comment by vitiral** [comment]
can you give some specific instances? I am rewriting them right now.

Thanks for the bug report!

**Comment by vitiral** [comment]
I've overhauled the docs. Can you let me know your thoughts?

**Comment by iqualfragile** [comment]
the confusing partof things are gone, but so is almost all information!
the user guide assumes familiarity with how requirement tracking works, and only explains artifacts specific syntax, and even that is properly explained.
if you read the user guide without having prior knowledge you do not gain anything by having done so.
it should introduce the tool in a way that an interested reader, that by chance happened to stumble upon this tool, without knowing what it does and what its good for, can understand and use its basic functionality after reading it.

**Comment by vitiral** [comment]
So you think the summary section should be more in depth? That's what I meant for the overview section to do, but that makes sense

**Comment by iqualfragile** [comment]
i did not see the overview, maybe just merge the two documents into one? i generally only open links after i am done with the current document, and i would expect the user guide to not only contain a summary

**Comment by vitiral** [comment]
Ya I think I am going to make the current overview into a "cheat sheet" and try to improve the quick guide with your suggestions

**Comment by vitiral** [comment]
I think I've figured out part of the problem. There are 3 full kinds of documentation and they are scattered:
- the "hello world" overview/quick guide
- the "interactive tutorial" built into the tool
- the Simple Quality book: https://vitiral.gitbooks.io/simple-quality/

I think I'm going to reduce this to just a cheat sheet and the book. The interactive tutorial will still be built into the tool but you will do it as part of the book.

The "quick guide" will then be moved into the book and be a quick guide for the book. 

Thoughts?

**Comment by vitiral** [comment]
Just created PR #77. @iqualfragile plese move discussion to that issue.
