### ISSUE TITLE
Make docs for multiple partof better

### ISSUE THREAD

**Issue by iqualfragile** [vitiral/artifact#74]
the way it currently is its not clear that its possible for one artifact to be partof multiple other artifacts, and the syntax is not obvious either, as you need to put a "," in between, spaces are just silently stripped.

it would be better to use an actual toml array for this.

**Comment by vitiral** [comment]
It's a string array to allow for "spc-[foo, bar]". 

Need to make the docs better

**Comment by iqualfragile** [comment]
hmm, im not entirely sure this resolves the issue though. if you add special syntax to strings they are not strings anymore, but your custom datatype, which also means that your file is not a toml file anymore, and can not be read by a toml parser anymore, so i am not sure if that trade is worth it

**Comment by vitiral** [comment]
As far as toml is concerned they are just strings.

They are more human readable and writable, and that is what is important. If the user want's machine readable data they can export as json with `art ls --type json`
