### ISSUE TITLE
art server starts elm in debug mode

### ISSUE THREAD

**Issue by iqualfragile** [vitiral/artifact#75]
as it says in the title, the frontend is set to debug mode even on release builds.
version tested was artifact 0.6.1

**Comment by vitiral** [comment]
You mean it has the messages and everything in the lower right? I kind of like users to have that right now, do you think it's bad?

**Comment by iqualfragile** [comment]
well, i happen to know what elm is, but that is not something you can expect of all users, and those will be confused about what it is.

**Comment by vitiral** [comment]
I left it in mostly so people can file a bug report with the history. Maybe I can figure out a way to make a button that does that all for them
