### ISSUE TITLE
Tracking code documentation

### ISSUE THREAD

**Issue by loldrup** [vitiral/artifact#80]
Hi

I have a question regarding best practice for using Artifact for tracking general documentation work (not only requirements documentation), and more specifically: tracking code documentation progress. I am working on a code project that implements a bunch of kinda hairy algorithms. I would like to, 
1. document these algorithms, somehow, and
2. I'd also like to write some documentation about how control flows through the code.

As for the first requirement: it would be neat if I could somehow link the soon-to-be-written code-documentation to the relevant sections of the source code, just as Artifact links requirements to specific code sections.

To achieve this goal, using Artifact, I could 'misuse' Artifact, by actually putting my code documentation into specifications specified in Artifact. This would give me the desired linkage between source code and the code documentation. However, this makes Artifact's progress tracking moot: code documentation only documents code that is already written, so Artifact would always report that I am 100% complete, even though I might only have written 10% of the code documentation that I intend to write.

Alternatively, I could use Artifact to track code documentation as a separate project. Thus I could specify requirements for my code documentation and track progress by annotating my markdown files, just as I would annotate any other source code.
However, this loosens the linkage between specific source code files and the specific files that documents the code in these files.

It seems I can't have it all. What's the story for tracking code documentation using Artifact? Is there a better tool out there for my purpose?

**Comment by vitiral** [comment]
First, to clear up confusion, artifact links *specifications and/or tests* to source code, not requirements.

I'm fairly confused about your use case. Let me try and re-summarize and you can tell me where I am wrong:
1. you want to write your design specification
2. you want your design spec to link to your source code impelmentation (and documentation)
3. However, you want to use this to track the completion of your *documentation*, not the completion of your code.

Is that correct?

The main purpose of artifact is to write design docs and track where they are implemented (while also making code self documenting).

If you want to have a bunch of "TODO" completion points, you can just *not* link like this:

```
SPC-my-doc
```

Instead of
```
#SPC-my-doc
```

Then when you have finished the document you just add the missing `#`.

Does that help?

**Comment by loldrup** [comment]
Thanks for your reply. See my reply below

Den 28/02/2017 12.38 AM skrev "Garrett Berg" <notifications@github.com>:

First, to clear up confusion, artifact links *specifications and/or tests*
to source code, not requirements.

I'm fairly confused about your use case. Let me try and re-summarize and
you can tell me where I am wrong:

   1. you want to write your design specification
   2. you want your design spec to link to your source code impelmentation
   (and documentation)
   3. However, you want to use this to track the completion of your
   *documentation*, not the completion of your code.

Is that correct?

Yes!
And this leads to some questions:

1. How do I track the completion of my documentation? (to which you have
suggested an answer, down below)

2. can *all* kinds of documentation relating to code reasonably be
shoehorned into the form of a specification? In my mind, specifications
deals with all the interfaces that code presents, and there might be other
aspects of code behaviour that one would also like to link to specific
parts of the source code (such as algorithm design considerations,
algorithm mechanics, program control flow (eg. 'this part of the code does
the instantiations of all the constructors'))

3. Could it be a good idea to treat documentation (any doc that goes beyond
requirements specification) as source code in itself? Thus using Artifact
to track the completion of this documentation, just as it tracks real
source code? This could perhaps be neat for my use case, but perhaps also
for others. I see that the Artifact project has a wiki that documents all
the doc aspects that goes beyond mere requirements specification. But how
complete is this Wiki? Are there known requirements for the wikis content
that hasn't yet been fulfilled? Could Artifact be used to track these
questions?
Further on, I guess some parts of the Wiki is tightly associated to
specific parts of the source code (or at least we could imagine this to be
the case). Could Artifact be expanded to also track to which extend
documentation (documentation that goes beyond specification) has documented
specific 'documentation craving' parts of the source code?

The main purpose of artifact is to write design docs and track where they
are implemented (while also making code self documenting).

How does it become self documenting? By shoehorning all documentation
aspects into the form of a specification?

If you want to have a bunch of "TODO" completion points, you can just *not*
link like this:

SPC-my-doc

Instead of

#SPC-my-doc

Then when you have finished the document you just add the missing #.

Does that help?


Yes this will help, but it doesn't exactly give me full on documentation
requirements fulfillment tracking.

My desired workflow would be something like this:

I write down requirements for my documentation (high level categories that
I want my documentation to cover).
Whenever I work on my source code, and I spot a component
(function/module/constructor/etc.) that really needs documentation, I tag
it with the relevant documentation requirement tag (and also the functions
name).
Then I go write some documentation and tag it as documenting component X.
Then Artifact can tell me that, for requirement Q, I have documented
component X, but I'm still missing to document the components Y and Z.
Thus Artifact tracks to which extent I have actually written the
documentation that I have required of myself.

But maybe it's just be. Maybe I should just get into the habit of phrasing
all my documentation as a design specification. And live without full on
tracking of my documentation progress.

Thanks for your time :)

**Comment by vitiral** [comment]
> 1. How do I track the completion of my documentation? (to which you have suggested an answer, down below)

I would like to point out that while artifact **does** track completion that is mostly for convienience. If you want to track "task/story/epic" completion I would use an agile tool like Zenhub (zenhub is also free for open source projects).

Maybe I will eventually make a task/story/epic tracking tool... but artifact is not it.

It sounds like most of what you want to do would be better done with task tracking tools and some source code `#DOCME` tags.

The primary purpose of artifact is once you *have* documented your code anyone reading your code can see which specification it implements (the `#SPC-my-spec` will be right there in the doc string). Then they can read your design docs to get an idea how everything fits toghther (and see where everything is implemented in source code)

> there might be other aspects of code behaviour that one would also like to link to specific parts of the source code (such as algorithm design considerations, algorithm mechanics, program control flow (eg. 'this part of the code does the instantiations of all the constructors'))

This is why you can do this:

```
[SPC-function]
text = '''
function does awesome stuff and uses:
- [[SPC-function-algorithm1]] to do awesome stuff 1
- [[SPC-function-algorithm2]] to do awesome stuff 2
'''

[SPC-function-algorithm1]
text = '''
algorithm that is awesome
'''

[SPC-function-algorithm2]
text = '''
another algorithm that is awesome
'''
```

The `[[...]]` notation was just released in version 0.6.2

**Comment by loldrup** [comment]
So the [[...]] notation is equivalent to the 'partof' notation used when
defining requirements?

Den 28/02/2017 5.28 PM skrev "Garrett Berg" <notifications@github.com>:

**Comment by vitiral** [comment]
No, it doesn't do anything but help with documentation. When you render it it the web-ui it creates a link
