### ISSUE TITLE
Use tabwriter to format output

### ISSUE THREAD

**Issue by Geemili** [vitiral/artifact#81]
Right now the program's output is a bit ugly and hard to read because the tables columns are not aligned. [tabwriter](https://github.com/BurntSushi/tabwriter) would make it easy to output nice, aligned columns.

**Comment by vitiral** [comment]
Thanks for the suggestion!

**Comment by vitiral** [comment]
thanks for the suggestion, it looks much better now!

**Comment by vitiral** [comment]
will be released in 0.6.3
