### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [vitiral/artifact#87]
According to [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay), rustc-serialize is scheduled to be deprecated in next month's beta release of Rust.

This would be a good time to let us know if there is any functionality you require from Serde before that happens.

**Comment by vitiral** [comment]
Thanks, I still depend on it for some features in my format command. I haven't had a chance to play around with toml serde. 

I would appreciate a pull request here if anyone was interested

**Comment by vitiral** [comment]
I'm currently waiting on this issue 

https://github.com/alexcrichton/toml-rs/issues/119

**Comment by dtolnay** [comment]
Got it. Based on the last comment in that issue, you might be waiting a long time unless you are able to implement it yourself.

**Comment by vitiral** [comment]
I'll take a stab at it on the bus and see where I can get

**Comment by dtolnay** [comment]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by vitiral** [comment]
getting closer in the linked PR. Now depend on this issue as well:

contain-rs/linked-hash-map#86
