### ISSUE TITLE
ArchLinux package

### ISSUE THREAD

**Issue by rubdos** [vitiral/artifact#89]
Hi,

I've been maintaining an [ArchLinux package](https://aur.archlinux.org/packages/artifact/) since you posted about this project on reddit.

If it interests you, you can put a link in the README file to it.

Ruben

PS. Do you guys have an IRC channel, or a Gitter room?

**Comment by vitiral** [comment]
Awesome, thanks! 

Gitter room link is on the wiki homepage 

https://github.com/vitiral/artifact/wiki

I'll include a link in the installation guide
