### ISSUE TITLE
Tutorial text is too wide for a 80 character terminal

### ISSUE THREAD

**Issue by porglezomp** [vitiral/artifact#90]
At minimum all the text in the tutorial should be formatted nicely for reading.

This is presumably a result of the fact that the text gets indented by 4 characters causing it to wrap.
Generalizing this issue though, Since the text is written in Markdown, I'm curious if it makes sense to re-format it in plain text for display at the width of the terminal.

**The current offending text:**
<img width="682" alt="screen shot 2017-03-06 at 1 32 51 pm" src="https://cloud.githubusercontent.com/assets/1690225/23623824/70cbdbc2-0271-11e7-8184-013b3aa76724.png">
**Reformatted to be at most 72 characters wide:**
<img width="682" alt="screen shot 2017-03-06 at 1 37 24 pm" src="https://cloud.githubusercontent.com/assets/1690225/23624023/335567bc-0272-11e7-9781-738540995829.png">

**Comment by vitiral** [comment]
hmm... that's a good point. Maybe I should remove the indent in `ls -l`?

Note: all tutorial text is formatted to 80 characters (this is guaranteed by a unit test)

**Comment by porglezomp** [comment]
I know that git recommends 72 characters specifically because it's intended to be displayed with a 4 character indentation, that way it's centered.

In my opinion the indent is good, but it might be worth investigating reducing it to 2 characters, which would leave 76 character long lines centered.

**Comment by porglezomp** [comment]
I got started re-wrapping the tutorial at 72 characters, I could try lowering the indentation to 2 and updating the test for 76 characters if you'd like.

**Comment by vitiral** [comment]
`art ls` is used extensivley and I would like for it to work on 80 character terminals. Writing requirements/etc to 72 characters is pretty annoying...

The color and the header makes it pretty clear where things are broken up. I think I prefer removing the indent all together

**Comment by porglezomp** [comment]
I'll write a PR to do this, since I'm interested in contributing.

**Comment by vitiral** [comment]
ok, sounds good! I *believe* the relevant code is somewhere in `src/cmd/display`

**Comment by vitiral** [comment]
Also, I think adding a newline at the end of the text field (when doing the "long" format) would be a good idea.

Probably best to just make sure that there are exactly two newlines, so [trim right](https://doc.rust-lang.org/std/string/struct.String.html#method.trim_right) off the end and then add two newlines.
