### ISSUE TITLE
Help message typos/formatting problems

### ISSUE THREAD

**Issue by porglezomp** [vitiral/artifact#93]
* [x] (1) In the help for `ls -p` it says "search FIELDS using pearl regexp SEARCH." when it should say "search FIELDS rust regexp."
* [x] (2) Inconsistent capitalization, "if set no output will be printed" vs "Prints help information."
* [ ] (3) Imperative vs declarative in messages: "Prints" or "sets" vs "start" or "delay"
* [x] (4) Some messages are too long for a 80 character terminal:
    ```
        -v             sets the level of verbosity, use multiple (up to 3) to increa
    se
    ```
* [x] (5) Some unnecessarily terse primary descriptions, e.g. there's no good reason to abbreviate "current directory" or "current folder" in
    ```
    art-init 
    initialize the repository in the cwd
    ```
* [X] ~(6) Should the descriptions be formatted like man pages?~ **No**
    ```
    art-init - Initialize the repository in the current directory
    ```
* [x] (7) The top level descriptions should probably be capitalized.
* [X] ~(8) I think that indenting the long versions of flags when there's no short version looks weird, but I can probably be persuaded to the contrary.~ **No**
* [x] (9) Some hanging indents are strangely deep:
    ```
        -w             If a file's formatting is different from art fmt,
                                           overwrite it with art fmt's vesion
    ```
* [ ] (10) Should "will be \*deactivated\* instead of activated" be formatted like this?
* [x] (11) Does `art-export` need "(only html currently)" in its primary description?
* [X] ~(12) `art help -h` produces an error.~ **It should produce an error, it is invalid**
* [x] (13) Clarify the `>` == `>100` explanation.
* [x] (14) The `--work-tree <work-tree>` causes indentation to be deeper than it needs to be, changing the value name to something like `--work-tree <PATH>` would reduce rightward drift.
* [x] (15) Enable colored help messages?
* [x] (16) Should we make all of the value names all caps like the manual ones are? Currently we have `-c <completed>` mixed with `-p <FIELDS>`.

**Comment by vitiral** [comment]
perl isn't really even valid, since it is a subset of perl. It actually uses the rust regexp syntax: https://doc.rust-lang.org/regex/regex/index.html#syntax

**Comment by porglezomp** [comment]
Okay, so just "regular expression" then

**Comment by porglezomp** [comment]
Oh wait, some of these complaints are based on 0.6.2, let me update to see if any of these are fixed.

**Comment by vitiral** [comment]
Some comments:
1. agreed: should be fixed to just say "regexp" and link the syntax
2. agreed: make them all standard like you suggest
3. agreed: make everything imperative like you suggest
4. agreed: reduce number of characters used in messages to width=40
5. agreed: replace the abbrev
6. agree (I think): the first character for all messages should be capitalized.
7. disagree: that is the way clap does it. I kind of like it actually.

**Comment by porglezomp** [comment]
Sorry, I added some more so I think your last few numbers got out of sync. I'll work on some of these after dinner.

**Comment by vitiral** [comment]
@porglezomp I think I updated it correctly

**Comment by vitiral** [comment]
wow, this is really a heck of a lot of things I was missing on the help page. I feel rather dumb haha

**Comment by porglezomp** [comment]
Is there any good reason to document that `>` == `>100`, since it doesn't immediately seem useful? Since it's inclusive I eventually figured out that means `>` means completed, should we say that instead?

**Comment by vitiral** [comment]
Maybe document that `<` is shorthand for `<0` and `>` is shorthand for `>100`. 

I would make it
```
filter by completeness (i.e. "<45") where "<" and ">" are inclusive.
Note:  ">" means ">100" and "<" means "<0"
```

**Comment by porglezomp** [comment]
What about the work-tree placeholder name?

**Comment by vitiral** [comment]
I would do `--work-tree PATH`

**Comment by porglezomp** [comment]
Do we want to enable the `wrap_help` feature in clip in order to get it wrapping at the terminal width instead of a fixed width?
Even if we don't, do we want to set the default wrap width to 80 characters?

**Comment by porglezomp** [comment]
What is an artifact "repository" called. Is repository the best word?

**Comment by porglezomp** [comment]
Since we want to capitalize the about messages, and the default clap messages are capitalized, I'm currently leaning towards capitalizing all the help messages. What do you think?

**Comment by vitiral** [comment]
btw, ignore any AppVeyor errors. I'm fixing them.

**Comment by porglezomp** [comment]
Repository is perfectly fine, I think. I'll make it consistent.

**Comment by porglezomp** [comment]
Just a note, to be done later, the error messages should probably also be capitalized?

**Comment by porglezomp** [comment]
Related to "color would be nice" do we want colored help messages?
<img width="682" alt="screen shot 2017-03-06 at 8 35 00 pm" src="https://cloud.githubusercontent.com/assets/1690225/23637909/6fb95c4c-02ac-11e7-877a-9b96bdfcc0e8.png">

**Comment by vitiral** [comment]
Yes please!

**Comment by porglezomp** [comment]
Okay, things left to do: Figure out how to override the help and version messages to make them `Print` instead of `Prints`, and if the value names should be all caps. Also, whatever we want to do with the emphasis.

**Comment by porglezomp** [comment]
I think the only way to replace the `--help` and `--version` messages is to implement `--help` and `--version` commands yourself, which seems like it's more work than I should do in this first commit.

**Comment by vitiral** [comment]
Ya don't do help and version here

**Comment by porglezomp** [comment]
It turns out capitalizing args adds angle braces inside the square braces, which looks bad. That's bad, so I left those lower case. I've submitted the PR now.

**Comment by vitiral** [comment]
I closed this while merging your PR. Those were some great changes!
