### ISSUE TITLE
Some of the docs refer to the executable as artifact instead of art

### ISSUE THREAD

**Issue by porglezomp** [vitiral/artifact#94]
While I was doing the artifact tutorial I noticed that the top and bottom of the tutorial suggested running `artifact tutorial ...` which—unless I'm missing something—doesn't work, and should be `art tutorial ...`.

I wonder if there's any reasonable way to test that all of the commands are possible to execute.
In the mean time, the docs should be inspected to find the places where this happens.

**Comment by vitiral** [comment]
for now I tested by searching for any instances of
```
'`artifact`
```
I should probably have a unit test that does that in the future, thanks
