### ISSUE TITLE
Line width should be computed in terms of Unicode width

### ISSUE THREAD

**Issue by porglezomp** [vitiral/artifact#96]
The code I wrote to limit the length of lines is currently counting bytes and making sure not to split any codepoints in half, but when there are many Unicode characters it won't correctly determine the width.

**Comment by porglezomp** [comment]
We already indirectly depend on `unicode-length` and `unicode-segmentation`, so it shouldn't be any trouble to add direct dependencies on them. I propose that if the string doesn't fit into the required width, then we iterate over the grapheme clusters until we reach the maximum appropriate unicode string width, then insert an ellipsis.

If we want to get fancy with ellipsis:
* If the string is all ASCII/Latin-1/etc then we shouldn't assume capabilities of the terminal and insert a 3 character pseudo-ellipsis `...`.
* If the string has fancy Unicode characters, then it should be safe to use more Unicode and insert a real ellipsis character `…`, thus letting us include two more characters of the original string.
This might be unneeded complexity though.

I'm also curious if we want to split lines on `\n` or if we want to follow the [Unicode Newline Guidelines](http://www.unicode.org/versions/Unicode4.0.0/ch05.pdf#G10213) for splitting lines.

**Comment by porglezomp** [comment]
@vitiral any opinions on these questions?

**Comment by vitiral** [comment]
I think don't do any fancy elipses, but it should support unicode width. 

I don't know what the unicode newline Guide is (not going to read it now) but imo just use /n

**Comment by porglezomp** [comment]
It turns out my first pass did exactly the things you requested, so it should be good.
