### ISSUE TITLE
Allow `art export` to export to another directory

### ISSUE THREAD

**Issue by rubdos** [vitiral/artifact#98]
Regarding [automatic builds](https://gitlab.com/rubdos/docker-artifact/blob/master/.gitlab-ci.yml) it would be nice if you could specify a flag to `art export` to have it export its html/markdown/latex/whatever to a separate directory.

That way, you don't have to clutter your main directory. Things like `.gitignore`-and-alike files only need one entry (namely the export directory), and one doesn't have to change `.gitignore` even if you guys decide to add new files or directories to the website.

**Comment by einsweniger** [comment]
I second this, I'd like to have it configurable in the settings, also.

**Comment by rubdos** [comment]
> I second this, I'd like to have it configurable in the settings, also.

Did I miss an existing issue on this? I didn't really check :/

**Comment by einsweniger** [comment]
Me neither, I assumed you did ;)

**Comment by vitiral** [comment]
Just so you know, I'm on vacation this week so I won't be working in this for a bit.

**Comment by rubdos** [comment]
@vitiral:
> Just so you know, I'm on vacation this week so I won't be working in this for a bit.

I knew, just making issues along the road when working with this.

@einsweniger :
> Me neither, I assumed you did ;)

I did now :D

**Comment by rubdos** [comment]
I am implementing this, doesn't seem difficult.
